spring:
  application:
    name: nodeInfo
  security:
    user:
      name: nodeInfo
      password: nodeInfo
  data:
    redis:
      ## 单机模式
      host: localhost # 地址
      port: 6379 # 端口
  thymeleaf:
    prefix: classpath:/templates-dev/
    suffix: .html
    cache: false
  web:
    resources:
      static-locations: classpath:/static-dev/
      #  mvc:
      #    static-path-pattern: /static-dev/**
      #    compression:
      #      enabled: true
      #      mime-types:
      #        - text/html
      #        - text/css
      #        - application/javascript


      #database: 0 # 指定数据库序号
#      connect-timeout: 1000 # 连接超时时间（毫秒）
#      timeout: 1000 # 操作超时时间（毫秒）
#      client-name: # 客户端名称（不知道干嘛用的）
#      client-type: lettuce # 驱动类型
#      # 连接池配置
#      lettuce:
#        pool:
#          min-idle: 1 # 最小空闲连接（默认0）
#          max-idle: 8 # 最大空闲连接（默认8）
#          max-active: 16 # 最大连接数（默认8，使用负值表示没有限制）
#          max-wait: -1ms # 最大阻塞等待时间（默认-1，负数表示没限制）
#      ssl:
#        enabled: false


